### ISSUE TITLE
SQL Importer Error: No suitable driver found for jdbc:postgresql

### ISSUE THREAD

**Issue by rychien-official** [omnisci/omniscidb#516]
Hi omniscidb team,

I'm having an issue when trying to export data from Postgres 9.5.3 to Omnisci, which is currently running in a docker container. Can you please provide some guidance? I'm a new user, so I apologize if this issue is an easy fix.

```
> java -cp /omnisci/bin/mapd-1.0-SNAPSHOT-jar-with-dependencies.jar:/tmp/postgresql-42.2.5.jar \
> com.mapd.utility.SQLImporter \
> -u admin -p HyperInteractive \
> -db xmera --port 6274 -t gccs_posit  \
> -su <redacted_username> -sp <redacted_pass> \
> -c "jdbc:postgresql://taps-development.sl-cloud.....<redacted>"  \
> -ss "select * from titan.gccs_posit limit 100"

2020-02-18 17:58:16 INFO  SQLImporter:executeQuery:345 - Connecting to database url :jdbc:postgresql://taps-development.sl-cloud....<redacted>
2020-02-18 17:58:16 ERROR SQLImporter:executeQuery:437 - SQLException - java.sql.SQLException: No suitable driver found for jdbc:postgresql://taps-development.sl-cloud.....
java.sql.SQLException: No suitable driver found for jdbc:postgresql://taps-development.sl-cloud.....
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
        at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
        at com.mapd.utility.SQLImporter.executeQuery(SQLImporter.java:346)
        at com.mapd.utility.SQLImporter.doWork(SQLImporter.java:334)
        at com.mapd.utility.SQLImporter.main(SQLImporter.java:319)
root@067361ea44c5:/omnisci#
```

Best,
Ryan

**Comment by rychien-official** [comment]
Solved. I needed to download the postgresql driver from https://jdbc.postgresql.org/download.html and load it via scp to /tmp
```
root@067361ea44c5:/# pwd
/
root@067361ea44c5:/# ls tmp
hsperfdata_root  mapd_log  postgresql-42.2.10.jar

```

Then, modify the java classpath with the additional jar file:
```
java -cp /omnisci/bin/mapd-1.0-SNAPSHOT-jar-with-dependencies.jar:/tmp/postgresql-42.2.10.jar \
com.mapd.utility.SQLImporter \
-u admin -p HyperInteractive \
-db xmera --port 6274 -t gccs_posit  \
-su <redacted_username>-sp <redacted_pass>\
-c "jdbc:postgresql://taps-development...."  \
-ss "select foreign_track_id from gccs_posit limit 100"  \
```
